apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: echo.hello.io
spec:
  group: hello.io
  names:
    kind: Echo
    listKind: EchoList
    plural: echos
    singular: echo
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Echo is the Schema for the echos API
          properties:
            spec:
              type: object
              properties:
                message:
                  description: Message to echo
                  type: string
              required:
                - message